#!/bin/bash
# Generated by Claude 3.5 👩‍💻

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check for required tools
for tool in git docker kurtosis; do
    if ! command_exists "$tool"; then
        echo -e "${RED}Error: $tool is not installed${NC}"
        case $tool in
            "git")./
                echo "Please install Git first"
                ;;
            "docker")
                echo "Please install Docker first: https://docs.docker.com/get-docker/"
                ;;
            "kurtosis")
                echo "Please install Kurtosis first: https://docs.kurtosis.com/install/"
                ;;
        esac
        exit 1
    fi
done

# Check if Docker daemon is running
if ! docker info >/dev/null 2>&1; then
    echo -e "${RED}Error: Docker daemon is not running${NC}"
    echo "Please start Docker daemon first"
    
    # Provide platform-specific instructions
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "On macOS, start Docker Desktop application"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "Run: sudo systemctl start docker"
    fi
    exit 1
fi

# Initialize and update submodules
echo -e "${YELLOW}Initializing and updating submodules...${NC}"

# Initialize submodules if not already initialized
if ! git submodule status &>/dev/null; then
    echo -e "${YELLOW}Initializing submodules...${NC}"
    if ! git submodule init; then
        echo -e "${RED}Failed to initialize submodules${NC}"
        exit 1
    fi
fi

# Update all submodules
echo -e "${YELLOW}Updating submodules...${NC}"
if ! git submodule update --init --recursive; then
    echo -e "${RED}Failed to update submodules${NC}"
    exit 1
fi

# Verify all required submodules are present
REQUIRED_SUBMODULES=(
    "rbuilder"
    "reth"
    "revm"
    "revm-inspectors"
    "ethereum-package"
    "protocol/lib/forge-std"
)

for submodule in "${REQUIRED_SUBMODULES[@]}"; do
    if [ ! -d "$submodule" ]; then
        echo -e "${RED}Error: Required submodule '$submodule' is missing${NC}"
        exit 1
    fi
done

echo -e "${GREEN}All submodules initialized and updated successfully${NC}"

# Function to build Docker image
build_image() {
    local name=$1
    local dockerfile=$2
    
    echo -e "${GREEN}Building ${name}...${NC}"
    
    if ! docker build ./ -t "gwyneth-${name}" -f "${dockerfile}"; then
        echo -e "${RED}Failed to build ${name}${NC}"
        return 1
    fi
    
    echo -e "${GREEN}Successfully built ${name}${NC}"
    return 0
}

# Main build process
echo -e "${GREEN}Starting build process...${NC}"

# Check if Dockerfiles exist
if [ ! -f "./reth/Dockerfile" ]; then
    echo -e "${RED}Error: Reth Dockerfile not found at ./reth/Dockerfile${NC}"
    exit 1
fi

if [ ! -f "./rbuilder/Dockerfile" ]; then
    echo -e "${RED}Error: Rbuilder Dockerfile not found at ./rbuilder/Dockerfile${NC}"
    exit 1
fi

# Build images
build_image "reth" "./reth/Dockerfile" || exit 1
build_image "rbuilder" "./rbuilder/Dockerfile" || exit 1

echo -e "${GREEN}All builds completed successfully!${NC}"

# Show image sizes and creation times
echo -e "\n${GREEN}Build Summary:${NC}"
docker images --format "table {{.Repository}}\t{{.Size}}\t{{.CreatedAt}}" | { grep "gwyneth-" || true; }  

# Check if network_params.yaml exists
if [ ! -f "./ethereum-package/network_params.yaml" ]; then
    echo -e "${RED}Error: network_params.yaml not found at ./ethereum-package/network_params.yaml${NC}"
    exit 1
fi

# Run Kurtosis
echo -e "\n${YELLOW}Running Kurtosis...${NC}"
if ! kurtosis run ./ethereum-package --args-file ethereum-package/network_params.yaml; then
    echo -e "${RED}Kurtosis command failed${NC}"
    exit 1
fi

echo -e "${GREEN}Kurtosis command completed successfully${NC}"