#!/bin/bash
# Generated by Claude 3.5 👩‍💻

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Run Kurtosis
echo -e "\n${YELLOW}Running Kurtosis...${NC}"
if ! kurtosis run ./ethereum-package --args-file ethereum-package/network_params.yaml; then
    echo -e "${RED}Kurtosis command failed${NC}"
    exit 1
fi

echo -e "${GREEN}Kurtosis command completed successfully${NC}"